# Get all contacts.
GET https://cse341-project1-c956.onrender.com/users


# Get contact by ID.
GET https://cse341-project1-c956.onrender.com/users/666e121c3da11a06c3ae1d01


# Create contact.
POST https://cse341-project1-c956.onrender.com/users HTTP/1.1
content-type: application/json

{
    "userName": "garett",
    "email": "garett.loveless@gmail.com",
    "name": "garett loveless",
    "ipaddress": "94.121.168.51"
}


# Update contact information.
PUT https://cse341-project1-c956.onrender.com/users/666e121c3da11a06c3ae1d01 HTTP/1.1
content-type: application/json

{
    "userName": "garet",
    "email": "garet.loveless@gmail.com",
    "name": "garet loveless",
    "ipaddress": "94.121.168.51"
}


# Delete a contact.
DELETE https://cse341-project1-c956.onrender.com/users/666e121c3da11a06c3ae1d01 HTTP/1.1